swagger: '2.0'
info:
  title: AzureAvdConnector1
  description: MCP streamable connector for Azure AVD MCP tools secured with OAuth (Entra ID).
  version: '1.0'
host: azure-mcp-multiservice-server.salmonmeadow-5a07697c.centralindia.azurecontainerapps.io
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    post:
      summary: Execute Azure AVD Connector 1 MCP Tool
      operationId: McpToolExecuteConnector1
      x-ms-agentic-protocol: mcp-streamable-1.0
      responses:
        '200':
          description: Success
      description: >-
        Execute Azure MCP Tools for managing Compute, Storage, Key Vault,
        Resource Groups, and Azure Virtual Desktop resources.
securityDefinitions:
  oauth2-auth:
    type: oauth2
    flow: accessCode
    tokenUrl: https://login.windows.net/common/oauth2/authorize
    scopes:
      b7800d5e-8f71-4f96-85f0-a618bd0536e5/.default: b7800d5e-8f71-4f96-85f0-a618bd0536e5/.default
    authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
security:
  - oauth2-auth:
      - b7800d5e-8f71-4f96-85f0-a618bd0536e5/.default
